//>>built
require({cache:{"JBrowse/Store/SeqFeature/BigWig/Window":function(){define(["dojo/_base/declare","dojo/_base/lang","./RequestWorker"],function(n,q,e){return n(null,{constructor:function(e,j,m,i){this.bwg=e;this.cirTreeOffset=j;this.cirTreeLength=m;this.isSummary=i},BED_COLOR_REGEXP:/^[0-9]+,[0-9]+,[0-9]+/,readWigData:function(e,j,m,i,q){(e=this.bwg.refsByName[e])?this.readWigDataById(e.id,j,m,i,q):i([])},readWigDataById:function(g,j,m,i,n){this.cirHeader?(new e(this,g,j,m,i,n)).cirFobRecur([this.cirTreeOffset+
48],1):(g=q.hitch(this,"readWigDataById",g,j,m,i),this.cirHeaderLoading?this.cirHeaderLoading.push(g):(this.cirHeaderLoading=[g],this.bwg.data.slice(this.cirTreeOffset,48).fetch(q.hitch(this,function(b){this.cirHeader=b;this.cirBlockSize=(new Int32Array(this.cirHeader,0,2))[1];dojo.forEach(this.cirHeaderLoading,function(b){b()});delete this.cirHeaderLoading}),n)))}})})},"JBrowse/Store/SeqFeature/BigWig/RequestWorker":function(){define(["dojo/_base/declare","dojo/_base/lang","JBrowse/Model/Range",
"jszlib/inflate"],function(n,q,e,g){var j=function(){console.log.apply(console,arguments)},m=n(null,{get:function(b){return this[{start:"min",end:"max",seq_id:"segment"}[b]||b]},tags:function(){return"start,end,seq_id,score,type,source".split(",")}}),i=n(m,{}),s=n(m,{});return n(null,{BIG_WIG_TYPE_GRAPH:1,BIG_WIG_TYPE_VSTEP:2,BIG_WIG_TYPE_FSTEP:3,constructor:function(b,d,c,a,f,h){this.window=b;this.source=b.bwg.name||void 0;this.blocksToFetch=[];this.outstanding=0;this.chr=d;this.min=c;this.max=a;
this.callback=f;this.errorCallback=h||function(a){console.error(a,a.stack,arguments.caller)}},cirFobRecur:function(b,d){this.outstanding+=b.length;for(var c=4+32*this.window.cirBlockSize,a,f=0;f<b.length;++f){var h=new e(b[f],Math.min(b[f]+c,this.window.cirTreeOffset+this.window.cirTreeLength));a=a?a.union(h):h}c=a.ranges();for(a=0;a<c.length;++a)this.cirFobStartFetch(b,c[a],d)},cirFobStartFetch:function(b,d,c){d.max();d.min();this.window.bwg.data.slice(d.min(),d.max()-d.min()).fetch(q.hitch(this,
function(a){for(var f=0;f<b.length;++f)d.contains(b[f])&&(this.cirFobRecur2(a,b[f]-d.min(),c),--this.outstanding,0==this.outstanding&&this.cirCompleted())}),this.errorCallback)},cirFobRecur2:function(b,d,c){var a=new Int8Array(b),f=new Int16Array(b),b=new Int32Array(b),a=a[d],f=f[d/2+1],d=d+4;if(0!=a)for(a=0;a<f;++a){var h=d/4,o=b[h],e=b[h+1],g=b[h+2],l=b[h+3],j=b[h+4]<<32|b[h+5],c=b[h+6]<<32|b[h+7];(o<this.chr||o==this.chr&&e<=this.max)&&(g>this.chr||g==this.chr&&l>=this.min)&&this.blocksToFetch.push({offset:j,
size:c});d+=32}else{for(var m=[],a=0;a<f;++a)h=d/4,o=b[h],e=b[h+1],g=b[h+2],l=b[h+3],j=b[h+4]<<32|b[h+5],(o<this.chr||o==this.chr&&e<=this.max)&&(g>this.chr||g==this.chr&&l>=this.min)&&m.push(j),d+=24;0<m.length&&this.cirFobRecur(m,c+1)}},cirCompleted:function(){this.blocksToFetch.sort(function(b,d){return(b.offset|0)-(d.offset|0)});0==this.blocksToFetch.length?this.callback([]):(this.features=[],this.tramp())},createFeature:function(b,d,c){c||(c={});var a=new i;a.segment=(this.window.bwg.refsByNumber[this.chr]||
{}).name;a.min=b;a.max=d;a.type="remark";a.source=this.source;for(k in c)a[k]=c[k];this.features.push(a)},maybeCreateFeature:function(b,d,c){b<=this.max&&d>=this.min&&this.createFeature(b,d,c)},tramp:function(){if(0==this.blocksToFetch.length)this.callback(this.features);else{var b=this.blocksToFetch[0];if(b.data){var d=new Uint8Array(b.data);if(this.window.isSummary)for(var c=new Int16Array(b.data),a=new Int32Array(b.data),f=new Float32Array(b.data),d=b.data.byteLength/32,c=0;c<d;++c){var h=a[8*
c],b=a[8*c+1],o=a[8*c+2],p=a[8*c+3],m=f[8*c+6];if(h==this.chr){h={score:m/p};if("bigbed"==this.window.bwg.type)h.type="density";this.maybeCreateFeature(b,o,h)}}else if("bigwig"==this.window.bwg.type)if(c=new Int16Array(b.data),a=new Int32Array(b.data),f=new Float32Array(b.data),h=a[0],b=a[1],h=a[3],o=a[4],p=d[20],d=c[11],p==this.BIG_WIG_TYPE_FSTEP)for(c=0;c<d;++c)p=f[c+6],this.maybeCreateFeature(b+c*h,b+c*h+o,{score:p});else if(p==this.BIG_WIG_TYPE_VSTEP)for(c=0;c<d;++c)b=a[2*c+6],p=f[2*c+7],this.maybeCreateFeature(b,
b+o,{score:p});else if(p==this.BIG_WIG_TYPE_GRAPH)for(c=0;c<d;++c)b=a[3*c+6],o=a[3*c+7],p=f[3*c+8],b>o&&(b=o),this.maybeCreateFeature(b,o,{score:p});else j("Currently not handling bwgType="+p);else if("bigbed"==this.window.bwg.type)for(a=0;a<d.length;){h=d[a+3]<<24|d[a+2]<<16|d[a+1]<<8|d[a+0];b=d[a+7]<<24|d[a+6]<<16|d[a+5]<<8|d[a+4];o=d[a+11]<<24|d[a+10]<<16|d[a+9]<<8|d[a+8];a+=12;for(c="";;)if(f=d[a++],0!=f)c+=String.fromCharCode(f);else break;var f={},l=c.split("\t");if(0<l.length)f.label=l[0];
if(1<l.length)f.score=stringToInt(l[1]);if(2<l.length)f.orientation=l[2];if(5<l.length&&(c=l[5],this.window.BED_COLOR_REGEXP.test(c)))f.override_color="rgb("+c+")";if(9>l.length)h==this.chr&&this.maybeCreateFeature(b,o,f);else if(h==this.chr&&b<=this.max&&o>=this.min){o=l[3]|0;h=l[4]|0;c=l[6]|0;p=l[7].split(",");m=l[8].split(",");f.type="bb-transcript";var r=new s;r.id=l[0];r.type="bb-transcript";r.notes=[];f.groups=[r];if(10<l.length){var r=l[9],l=l[10],i=new s;i.id=r;i.label=l;i.type="gene";f.groups.push(i)}l=
null;for(r=0;r<c;++r)i=(m[r]|0)+b,i=new e(i,i+(p[r]|0)),l=l?l.union(i):i;p=l.ranges();for(b=0;b<p.length;++b)c=p[b],this.createFeature(c.min(),c.max(),f);if(h>o&&(b=l.intersection(new e(o,h)))){f.type="bb-translation";o=b.ranges();for(b=0;b<o.length;++b)c=o[b],this.createFeature(c.min(),c.max(),f)}}}else j("Don't know what to do with "+this.window.bwg.type);this.blocksToFetch.splice(0,1);this.tramp()}else{for(var d=b.offset,n=b.size,b=1;b<this.blocksToFetch.length&&this.blocksToFetch[b].offset==d+
n;)n+=this.blocksToFetch[b].size,++b;this.window.bwg.data.slice(d,n).fetch(q.hitch(this,function(a){for(var b=0,f=0;b<n;){var c=this.blocksToFetch[f],h;0<this.window.bwg.uncompressBufSize?h=g(a,b+2,c.size-2):(h=new Uint8Array(c.size),arrayCopy(new Uint8Array(a,b,c.size),0,h,0,c.size),h=h.buffer);c.data=h;b+=c.size;++f}this.tramp()}),this.errorCallback)}}}})})},"JBrowse/Model/Range":function(){define(["dojo/_base/declare"],function(n){var q=n(null,{constructor:function(){this._ranges=2==arguments.length?
[{min:arguments[0],max:arguments[1]}]:0 in arguments[0]?dojo.clone(arguments[0]):[arguments[0]]},min:function(){return this._ranges[0].min},max:function(){return this._ranges[this._ranges.length-1].max},contains:function(e){for(var g=0;g<this._ranges.length;++g){var j=this._ranges[g];if(j.min<=e&&j.max>=e)return!0}return!1},isContiguous:function(){return 1<this._ranges.length},ranges:function(){return this._ranges.map(function(e){return new q(e.min,e.max)})},toString:function(){return this._ranges.map(function(e){return"["+
e.min+"-"+e.max+"]"}).join(",")},union:function(e){for(var e=this.ranges().concat(e.ranges()).sort(this.rangeOrder),g=[],j=e[0],m=1;m<e.length;++m){var i=e[m];i.min()>j.max()+1?(g.push(j),j=i):i.max()>j.max()&&(j=new q(j.min(),i.max()))}g.push(j);return 1==g.length?g[0]:new _Compound(g)},intersection:function(e){for(var g,j=this.ranges(),m=e.ranges(),i=j.length,n=m.length,b=0,d=0,c=[];b<i&&d<n;){g=j[b];var e=m[d],a=Math.max(g.min(),e.min()),f=Math.min(g.max(),e.max());f>=a&&c.push(new q(a,f));g.max()>
e.max()?++d:++b}return 0==c.length?null:1==c.length?c[0]:new _Compound(c)},coverage:function(){for(var e=0,g=this.ranges(),j=0;j<g.length;++j)var m=g[j],e=e+(m.max()-m.min()+1);return e},rangeOrder:function(e,g){2>arguments.length&&(g=e,e=this);return e.min()<g.min()?-1:e.min()>g.min()?1:e.max()<g.max()?-1:g.max()>e.max()?1:0}});return q})}}});
define("JBrowse/Store/SeqFeature/BigWig","dojo/_base/declare,dojo/_base/lang,dojo/_base/array,dojo/_base/url,JBrowse/has,JBrowse/Store/SeqFeature,JBrowse/Store/DeferredStatsMixin,JBrowse/Store/DeferredFeaturesMixin,./BigWig/Window,JBrowse/Util,JBrowse/Model/XHRBlob".split(","),function(n,q,e,g,j,m,i,s,b,d,c){return n([m,i,s],{BIG_WIG_MAGIC:-2003829722,BIG_BED_MAGIC:-2021002517,BIG_WIG_TYPE_GRAPH:1,BIG_WIG_TYPE_VSTEP:2,BIG_WIG_TYPE_FSTEP:3,constructor:function(a){this.data=a.blob||new c(this.resolveUrl(a.urlTemplate||
"data.bigwig"));this.name=a.name||this.data.url&&(new g(this.data.url)).path.replace(/^.+\//,"")||"anonymous";this._load()},_getGlobalStats:function(a){var b=this._globalStats||{};if(!("scoreMean"in b))b.scoreMean=b.basesCovered?b.scoreSum/b.basesCovered:0;if(!("scoreStdDev"in b))b.scoreStdDev=this._calcStdFromSums(b.scoreSum,b.scoreSumSquares,b.basesCovered);a(b)},_load:function(){var a=this;a.data.slice(0,512).fetch(function(b){if(b){a.fileSize=b.fileSize;var c=new Int16Array(b),d=new Int32Array(b);
if(d[0]==a.BIG_WIG_MAGIC)a.type="bigwig";else if(d[0]==a.BIG_BED_MAGIC)a.type="bigbed";else{console.error("Format "+d[0]+" not supported");a._failAllDeferred("Format "+d[0]+" not supported");return}a.version=c[2];a.numZoomLevels=c[3];a.chromTreeOffset=d[2]<<32|d[3];a.unzoomedDataOffset=d[4]<<32|d[5];a.unzoomedIndexOffset=d[6]<<32|d[7];a.fieldCount=c[16];a.definedFieldCount=c[17];a.asOffset=d[9]<<32|d[10];a.totalSummaryOffset=d[11]<<32|d[12];a.uncompressBufSize=d[13];a.zoomLevels=[];for(c=0;c<a.numZoomLevels;++c)a.zoomLevels.push({reductionLevel:d[6*
c+16],dataOffset:d[6*c+18]<<32|d[6*c+19],indexOffset:d[6*c+20]<<32|d[6*c+21]});a.totalSummaryOffset?Float64Array?function(){var c=new Uint32Array(b,a.totalSummaryOffset,2),d=new Float64Array(b,a.totalSummaryOffset+8,4);a._globalStats={basesCovered:c[0]<<32|c[1],scoreMin:d[0],scoreMax:d[1],scoreSum:d[2],scoreSumSquares:d[3]}}.call():console.warn("BigWig "+a.data.url+" total summary not available, this web browser is not capable of handling this data type."):console.warn("BigWig "+a.data.url+" has no total summary data.");
a._readChromTree(function(){a._deferred.features.resolve({success:!0});a._deferred.stats.resolve({success:!0})},dojo.hitch(a,"_failAllDeferred"))}else this._failAllDeferred("BBI header not readable")},dojo.hitch(this,"_failAllDeferred"))},_readInt:function(a,b){return a[b+3]<<24|a[b+2]<<16|a[b+1]<<8|a[b]},_readShort:function(a,b){return a[b+1]<<8|a[b]},_readChromTree:function(a,b){var c=this;this.refsByNumber={};this.refsByName={};for(var d=this.unzoomedDataOffset;0!=d%4;)++d;var e=this._readInt,
g=this._readShort;this.data.slice(this.chromTreeOffset,d-this.chromTreeOffset).fetch(function(b){if(j("typed-arrays")){var d=new Uint8Array(b),b=new Int32Array(b,0,6);if(2026540177!==b[0])throw"parse error: not a Kent bPlusTree";var f=b[2],m=function(a){if(a>=d.length)throw"reading beyond end of buffer";for(var b=d[a],j=g(d,a+2),a=a+4,l=0;l<j;++l)if(b){for(var i="",o=0;o<f;++o){var n=d[a++];0!=n&&(i+=String.fromCharCode(n))}o=e(d,a);n=e(d,a+4);a+=8;n={name:i,id:o,length:n};c.refsByName[c.browser.regularizeReferenceName(i)]=
n;c.refsByNumber[o]=n}else a+=f,i=e(d,a+4)<<32|e(d,a),a+=8,i-=c.chromTreeOffset,m(i)};m(32);a.call(c,c)}else c._failAllDeferred("Web browser does not support typed arrays")},b)},hasRefSeq:function(a,b,c){var d=this,a=d.browser.regularizeReferenceName(a);this._deferred.features.then(function(){b(a in d.refsByName)},c)},_getFeatures:function(a,b,c,d){var g=this.browser.regularizeReferenceName(a.ref),i=a.start,j=a.end;(a=a.basesPerSpan?this.getView(1/a.basesPerSpan):a.scale?this.getView(scale):this.getView(1))?
a.readWigData(g,i,j,dojo.hitch(this,function(a){e.forEach(a||[],b);c()}),d):c()},getUnzoomedView:function(){if(!this.unzoomedView){var a=4E3;this.zoomLevels[0]&&(a=this.zoomLevels[0].dataOffset-this.unzoomedIndexOffset);this.unzoomedView=new b(this,this.unzoomedIndexOffset,a,!1)}return this.unzoomedView},getView:function(a){if(!this.zoomLevels||!this.zoomLevels.length)return null;if(!this._viewCache||this._viewCache.scale!=a)this._viewCache={scale:a,view:this._getView(a)};return this._viewCache.view},
_getView:function(a){for(var a=1/a,c=this.zoomLevels.length-1;0<c;c--){var d=this.zoomLevels[c];if(d&&d.reductionLevel<=a)return new b(this,d.indexOffset,c<this.zoomLevels.length-1?this.zoomLevels[c+1].dataOffset-d.indexOffset:this.fileSize-4-d.indexOffset,!0)}return this.getUnzoomedView()}})});